### ISSUE TITLE
ExecutionContext same or different?

### ISSUE THREAD

**Issue by ArthurSonzogni** [steimelchrome/document-pip-explainer#7]
Out of curiosity, in the Chrome implementation, do you believe this is going to create:
- A brand new context with a new ExecutionContext and Document like the iframe/popup would. It comes with a new RenderFrame[Host] and [Web]LocalFrame.
- A "light" Document attached to the previous "main" Document, and reuse the same ExecutionContext. Something similar to using: [Document::Create(Document&)](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/dom/document.h;l=324;bpv=0;bpt=1). I guess this is currently in use to implement the JS API:
```js
DOMImplementation.createHTMLDocument()
```

Knowing if the PIP document and the main document will be considered from the same or different ExecutionContext is going to have an important impact on how this interact with every other features. Basically, do they constitute 1 or 2 actors.

I think considering the new Document to be part of the caller's one to be much simpler to think about. I haven't given it much thought though.

**Comment by domenic** [comment]
> A "light" Document attached to the previous "main" Document, and reuse the same ExecutionContext. 

I think this would break a lot of assumptions in the web platform, which currently assume that there is a 1:1 correspondence between "active" documents (i.e. documents in which various APIs, including rendering, work) and `Window`s/`ExecutionContext`s/etc.

The "synthetic" documents created by `document.implementation.createHTMLDocument()` are basically DOM-node-containers. They cannot be displayed to the user, run script, or do anything else interesting.

**Comment by ArthurSonzogni** [comment]
Okay, okay. So this is really going to work like a real popup, but which is guaranteed to stay on the initial empty document. I see. Thanks!

**Comment by domenic** [comment]
Well, I'm not @steimelchrome, so I'm not sure what they're proposing, but that's my hope :).

**Comment by steimelchrome** [comment]
That's correct, the ExecutionContext will be different between the opener window and the PiP window

**Comment by ArthurSonzogni** [comment]
Great! Thanks for confirming!

We took a look at the design doc today and found:
https://docs.google.com/document/d/1Pm794yGCCTdGUdv9nH1GReAoOLY54cvSl08pc_ElxD0/edit?resourcekey=0-mujLPnueja5ORele7QwOhw&disco=AAAAPkJgCTA
```
The two documents will operate under the same execution context
```

I guess the design doc is stale? You probably wanted to say the two document will be considered same-origin with direct synchronous access, but they are using a different ExecutionContext.

(You can close this issue if you want)

**Comment by steimelchrome** [comment]
Yep sorry the design doc is stale. I'll update that part. Thanks for spotting that!
